### ISSUE TITLE
There is a typo in the app

### ISSUE THREAD

**Issue by yumec** [PluralsightDemoOrganition/ideal-train#2]
I found a typo on the second screen of the app. and you need to fix it now!!

**Comment by yokideng** [comment]
I looked at this. and it's spelled correctly. Where did you see it?

**Comment by yokideng** [comment]
hmmm, let me check.
it's hard to see, where do you find it.
can you provide me more information.







在 2016-04-05 03:21:09，"yume chen" <notifications@github.com> 写道：


Assigned #2 to @yokideng.

**Comment by yumec** [comment]
it's gone. it mean i can not find it any more.....lol

**Comment by yokideng** [comment]
haha.....
